CREATE DATABASE FoodExpress;
USE FoodExpress;

CREATE TABLE Vendor(
VendorID INT PRIMARY KEY,
Location Varchar(255) NOT NULL
);
Create TABLE MenuItem(
ItemID INT PRIMARY KEY,
MenuName VARCHAR(50) NOT NULL,
Price DECIMAL(10,2) NOT NULL
);
CREATE TABLE Customer(
CustomerID INT PRIMARY KEY,
Email VARCHAR(50) NOT NULL,
Address VARCHAR(225) NOT NULL,
Phone VARCHAR(50) NOT NULL,
);


CREATE TABLE Orders(
OrderID INT PRIMARY KEY,
Statue VARCHAR(50) NOT NULL,
OrderTime VARCHAR(50) NOT NULL,
ItemID INT,
CustomerID INT,
FOREIGN KEY (ItemID) REFERENCES MenuItem(ItemID),
FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) 
);


CREATE TABLE Driver(
DriverID INT PRIMARY KEY,
Phone VARCHAR(50) NOT NULL 
);

CREATE TABLE Delivery(
DeliveryID INT PRIMARY KEY,
DeliveryStatus VARCHAR(50) NOT NULL,
Dropoff VARCHAR(50) NOT NULL,
DeliveryTime VARCHAR(50) NOT NULL,
OrderID INT,
DriverID INT,
FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
FOREIGN KEY (DriverID) REFERENCES Driver(DriverID)
);